# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
# 工具相关配置
gfcli:
  # 工具编译配置
  build:
    name: "shop"
    arch: "amd64"
    system: "linux,darwin,windows"
    mod: ""
    cgo: 0

  # dao生成
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/gf_db_demo?loc=Local"
        jsonCase: "CamelLower"
        descriptionTag: true
        noModelComment: false
        overwriteDao: true
        stdTime: false
        gJsonSupport: true
